apiVersion: 1

datasources:
  - name: Vega Postgres
    type: postgres
    access: proxy
    isDefault: true
    url: postgres:5432
    user: vega_user
    secureJsonData:
      password: vega_password
    jsonData:
      database: vega_db
      sslmode: disable


